/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Windows
 */
public class CalculadoraTeatro extends javax.swing.JFrame {

    // Variables para guardar la pérdida total por cada categoría
    private double perdidaTotalCat1 = 0;
    private double perdidaTotalCat2 = 0;
    private double perdidaTotalCat3 = 0;
    private double perdidaTotalCat4 = 0;
    private double perdidaTotalCat5 = 0;

    // Aquí continúa el código que NetBeans generó
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraTeatro.class.getName());

    /**
     * Creates new form CalculadoraTeatro
     */
    public CalculadoraTeatro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPrecioEntrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEdadCliente = new javax.swing.JTextField();
        btnProcesar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblPerdidaCat1 = new javax.swing.JLabel();
        lblPerdidaCat2 = new javax.swing.JLabel();
        lblPerdidaCat3 = new javax.swing.JLabel();
        lblPerdidaCat4 = new javax.swing.JLabel();
        lblPerdidaCat5 = new javax.swing.JLabel();
        lblPrecioConDescuento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Precio Único de la Entrada:");

        jLabel2.setText("Edad del Cliente:");

        btnProcesar.setText("Procesar Cliente");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        jLabel3.setText("Pérdida Total por Categoría:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrecioConDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnProcesar)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPrecioEntrada, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEdadCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblPerdidaCat5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(lblPerdidaCat4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPerdidaCat3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPerdidaCat2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPerdidaCat1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPerdidaCat1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPerdidaCat2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEdadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPerdidaCat3)
                        .addGap(12, 12, 12)
                        .addComponent(lblPerdidaCat4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesar)
                    .addComponent(lblPerdidaCat5))
                .addGap(31, 31, 31)
                .addComponent(lblPrecioConDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        // TODO add your handling code here:
         try {
        // 1. Obtener los valores de los campos de texto
        double precioBase = Double.parseDouble(txtPrecioEntrada.getText());
        int edad = Integer.parseInt(txtEdadCliente.getText());
        double descuento = 0;
        double precioFinal = 0; // Agregamos una variable para el precio final

        // 2. Limpiamos la etiqueta de precio final y de error
        lblPrecioConDescuento.setText("");
        lblPerdidaCat1.setText("Pérdida Categoría 1: $" + String.format("%.2f", perdidaTotalCat1)); // Reiniciamos el mensaje de error

        // 3. Aplicar la lógica de la imagen (if-else if)
        if (edad < 5) {
            lblPrecioConDescuento.setText("Error: Menores de 5 no pueden entrar.");
        } else if (edad >= 5 && edad <= 14) {
            descuento = precioBase * 0.35;
            perdidaTotalCat1 += descuento;
            precioFinal = precioBase - descuento; // Calculamos el precio final
        } else if (edad >= 15 && edad <= 19) {
            descuento = precioBase * 0.25;
            perdidaTotalCat2 += descuento;
            precioFinal = precioBase - descuento;
        } else if (edad >= 20 && edad <= 45) {
            descuento = precioBase * 0.10;
            perdidaTotalCat3 += descuento;
            precioFinal = precioBase - descuento;
        } else if (edad >= 46 && edad <= 65) {
            descuento = precioBase * 0.25;
            perdidaTotalCat4 += descuento;
            precioFinal = precioBase - descuento;
        } else if (edad >= 66) {
            descuento = precioBase * 0.35;
            perdidaTotalCat5 += descuento;
            precioFinal = precioBase - descuento;
        }
        
        // 4. Mostramos el precio final en la nueva etiqueta, solo si se calculó
        if (precioFinal > 0) {
            lblPrecioConDescuento.setText("Precio de la entrada con descuento: $" + String.format("%.2f", precioFinal));
        }

        // 5. Actualizamos la interfaz con los totales acumulados (esto ya lo tenías)
        lblPerdidaCat1.setText("Pérdida Categoría 1: $" + String.format("%.2f", perdidaTotalCat1));
        lblPerdidaCat2.setText("Pérdida Categoría 2: $" + String.format("%.2f", perdidaTotalCat2));
        lblPerdidaCat3.setText("Pérdida Categoría 3: $" + String.format("%.2f", perdidaTotalCat3));
        lblPerdidaCat4.setText("Pérdida Categoría 4: $" + String.format("%.2f", perdidaTotalCat4));
        lblPerdidaCat5.setText("Pérdida Categoría 5: $" + String.format("%.2f", perdidaTotalCat5));
        
        // Limpiamos la edad para el siguiente cliente
        txtEdadCliente.setText("");

    } catch (NumberFormatException e) {
        lblPrecioConDescuento.setText("Error: Ingrese números válidos.");
    }
    }//GEN-LAST:event_btnProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraTeatro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPerdidaCat1;
    private javax.swing.JLabel lblPerdidaCat2;
    private javax.swing.JLabel lblPerdidaCat3;
    private javax.swing.JLabel lblPerdidaCat4;
    private javax.swing.JLabel lblPerdidaCat5;
    private javax.swing.JLabel lblPrecioConDescuento;
    private javax.swing.JTextField txtEdadCliente;
    private javax.swing.JTextField txtPrecioEntrada;
    // End of variables declaration//GEN-END:variables
}
